In [1]:
import torch

In [4]:
state_dict = torch.load(r'checkpoints/bitnet_2b_4t/model_state_fp16.pt')

In [6]:
print(state_dict.keys())

dict_keys(['tok_embeddings.weight', 'layers.0.attention.wqkv.weight', 'layers.0.attention.wo.weight', 'layers.0.attention.attn_sub_norm.weight', 'layers.0.feed_forward.w13.weight', 'layers.0.feed_forward.w2.weight', 'layers.0.feed_forward.ffn_sub_norm.weight', 'layers.0.attention_norm.weight', 'layers.0.ffn_norm.weight', 'layers.1.attention.wqkv.weight', 'layers.1.attention.wo.weight', 'layers.1.attention.attn_sub_norm.weight', 'layers.1.feed_forward.w13.weight', 'layers.1.feed_forward.w2.weight', 'layers.1.feed_forward.ffn_sub_norm.weight', 'layers.1.attention_norm.weight', 'layers.1.ffn_norm.weight', 'layers.2.attention.wqkv.weight', 'layers.2.attention.wo.weight', 'layers.2.attention.attn_sub_norm.weight', 'layers.2.feed_forward.w13.weight', 'layers.2.feed_forward.w2.weight', 'layers.2.feed_forward.ffn_sub_norm.weight', 'layers.2.attention_norm.weight', 'layers.2.ffn_norm.weight', 'layers.3.attention.wqkv.weight', 'layers.3.attention.wo.weight', 'layers.3.attention.attn_sub_norm.wei

In [7]:
state_dict['tok_embeddings.weight'].shape

torch.Size([128256, 2560])

In [9]:
torch.allclose(state_dict['output.weight'], state_dict['tok_embeddings.weight'])


True

In [54]:
tensor_name = 'layers.0.feed_forward.w13.weight'
# tensor_name = 'layers.0.attention.wqkv.weight'

In [57]:
state_dict_before = torch.load('./checkpoints/model_state.pt')
state_dict_after = torch.load('./checkpoints/model_state_fp16.pt')

In [55]:
state_dict_before[tensor_name], state_dict_after[tensor_name]

(tensor([[ 0.7734,  1.8438,  1.1562,  ..., -0.1270, -0.4160, -3.2969],
         [ 0.1943,  0.9219,  0.7852,  ...,  1.3203, -3.1406,  0.9844],
         [ 0.8164,  1.4453, -0.7578,  ..., -1.3594, -1.9219, -2.3750],
         ...,
         [-0.2139,  0.9180, -5.6562,  ...,  0.8164,  0.3457, -4.4688],
         [-0.9336, -0.1816, -0.1030,  ...,  4.4375, -0.9062, -0.1201],
         [ 3.4688, -3.0156, -0.9180,  ..., -0.9883,  0.9180, -1.1484]],
        dtype=torch.bfloat16),
 tensor([[ 0.0000,  1.5547,  1.5547,  ..., -0.0000, -0.0000, -1.5547],
         [ 0.0000,  1.5547,  1.5547,  ...,  1.5547, -1.5547,  1.5547],
         [ 1.5547,  1.5547, -0.0000,  ..., -1.5547, -1.5547, -1.5547],
         ...,
         [-0.0000,  1.8281, -1.8281,  ...,  0.0000,  0.0000, -1.8281],
         [-1.8281, -0.0000, -0.0000,  ...,  1.8281, -0.0000, -0.0000],
         [ 1.8281, -1.8281, -1.8281,  ..., -1.8281,  1.8281, -1.8281]],
        dtype=torch.bfloat16))

In [7]:
state_dict_ref = torch.load('checkpoints/bitnet_2b_4t/model_state_fp16.pt')

In [58]:
# torch.allclose(state_dict_ref[tensor_name], state_dict_before[tensor_name])
state_dict_ref[tensor_name], state_dict_after[tensor_name]

(tensor([[ 0.0000,  1.5512,  1.5512,  ..., -0.0000, -0.0000, -1.5512],
         [ 0.0000,  1.5512,  1.5512,  ...,  1.5512, -1.5512,  1.5512],
         [ 1.5512,  1.5512, -0.0000,  ..., -1.5512, -1.5512, -1.5512],
         ...,
         [-0.0000,  1.8309, -1.8309,  ...,  0.0000,  0.0000, -1.8309],
         [-1.8309, -0.0000, -0.0000,  ...,  1.8309, -0.0000, -0.0000],
         [ 1.8309, -1.8309, -1.8309,  ..., -1.8309,  1.8309, -1.8309]]),
 tensor([[ 0.0000,  1.5547,  1.5547,  ..., -0.0000, -0.0000, -1.5547],
         [ 0.0000,  1.5547,  1.5547,  ...,  1.5547, -1.5547,  1.5547],
         [ 1.5547,  1.5547, -0.0000,  ..., -1.5547, -1.5547, -1.5547],
         ...,
         [-0.0000,  1.8281, -1.8281,  ...,  0.0000,  0.0000, -1.8281],
         [-1.8281, -0.0000, -0.0000,  ...,  1.8281, -0.0000, -0.0000],
         [ 1.8281, -1.8281, -1.8281,  ..., -1.8281,  1.8281, -1.8281]],
        dtype=torch.bfloat16))

In [30]:
import safetensors

In [31]:
import safetensors.torch


st = safetensors.torch.load_file('checkpoints/bitnet-b1.58-2B-4T-bf16/model.safetensors')

In [37]:
st['model.layers.0.mlp.down_proj.weight']

tensor([[-1.1328, -0.4648,  6.4062,  ..., -2.9844, -5.5000,  0.7070],
        [ 3.5469,  1.6016, -1.4844,  ...,  1.0703,  4.7500,  1.0781],
        [ 9.8750,  2.2344, -5.5000,  ..., -2.4688,  1.0312, -0.7891],
        ...,
        [-2.2031, -2.0156, -0.4297,  ...,  0.8633,  9.9375, -3.6562],
        [-1.0391, -1.5391, -5.9062,  ..., -1.4609, -1.1953,  7.5000],
        [ 2.6094,  0.8984, 10.0625,  ..., -3.5469,  2.4375,  1.0547]],
       dtype=torch.bfloat16)

In [38]:
def quant_weight_fp16(weight):
    s = 1.0 / weight.abs().mean().clamp_(min=1e-5)
    new_weight = (weight * s).round().clamp(-1, 1) / s
    return new_weight
    # return weight

In [39]:
quant_weight_fp16(st['model.layers.0.mlp.down_proj.weight'])

tensor([[-2.1562, -0.0000,  2.1562,  ..., -2.1562, -2.1562,  0.0000],
        [ 2.1562,  2.1562, -2.1562,  ...,  0.0000,  2.1562,  0.0000],
        [ 2.1562,  2.1562, -2.1562,  ..., -2.1562,  0.0000, -0.0000],
        ...,
        [-2.1562, -2.1562, -0.0000,  ...,  0.0000,  2.1562, -2.1562],
        [-0.0000, -2.1562, -2.1562,  ..., -2.1562, -2.1562,  2.1562],
        [ 2.1562,  0.0000,  2.1562,  ..., -2.1562,  2.1562,  0.0000]],
       dtype=torch.bfloat16)